### ISSUE TITLE
Search function in themelibrary

### ISSUE THREAD

**Issue by olivertzeng** [Faf4a/ThemeLibrary#2]

**Comment by Faf4a** [comment]
Mind explaining a bit further what the issue is with the search function?

**Comment by olivertzeng** [comment]
> Mind explaining a bit further what the issue is with the search function?

Wait does that mean there is a search function in themelibrary? I actually don't see one

**Comment by Faf4a** [comment]
Yes, there's one at the top of the Theme Library tab.
![image](https://github.com/user-attachments/assets/c18ba6de-d86a-4c99-81ef-bdbf5e7e51b6)

**Comment by olivertzeng** [comment]
> Yes, there's one at the top of the Theme Library tab.
> 
> ![image](https://github.com/user-attachments/assets/c18ba6de-d86a-4c99-81ef-bdbf5e7e51b6)
> 
> 

I'll check my own css lmao
